### ISSUE TITLE
The variable "name" is the Snippet "mtp" is not working

### ISSUE THREAD

**Issue by GaetanRouzies** [erickeno/meteorjs-snippets-es6#2]
Hello,

The "mtp" snippet is not working fine due to this code:
[`<template name="{1:name}">`](https://github.com/erickeno/meteorjs-snippets-es6/blob/master/snippets/meteor.cson#L163)

That should be `<template name="${1:name}">`, just the dollar sign is missing. :) 
Thanks you for this atom package

**Comment by erickeno** [comment]
Thanks, I have updated it.
